### ISSUE TITLE
Playlist not working with IE9

### ISSUE THREAD

**Issue by m2d4yh** [mediafront/osmplayer#23]
There seem to be several issues, one is that the css needs to be modified to allow for 100% player size.. the other is that a (mixed) playlist.xml will not function in IE9 at all. It seems to work on the OSM main site but not in the downloaded files.
I get a shrunken player and nothing will load off of the playlist.. I am running it as a standalone player.

**Comment by m2d4yh** [comment]
I should mention that it works in FF, Opera, Chrome and Safari with no problems at all and I have always hated IE because it sucks so bad but some of my visitors are stupid enough to use it ;) LOL

**Comment by travist** [comment]
I think I got this working by adding `<!DOCTYPE html>` to the top of the HTML5 file and then being explicit about the height.  

https://github.com/mediafront/osmplayer/commit/b59aece6a905f6907a3b9b22f06bb33a46be6ebe
