### ISSUE TITLE
Is it possible...?

### ISSUE THREAD

**Issue by Zizzilius** [mediafront/osmplayer#34]
Hello.
I just happen to be a newbie in all this stuff.

But just a technical question:
Is it possible to use different online services in 1 playlist?

I mean - 2 vids from youtube, than a video from a social-website (smth like Facebook, but with more feautures - vk.com) and in the end video from official TV-webpage where i found thee own video-player system.

**Comment by travist** [comment]
You can use a mixture of Vimeo, YouTube, HTML5, Flash, and Limelight CDN within the same playlist.  If you need other providers than that, then those are currently not supported.
