### ISSUE TITLE
playlist.xml

### ISSUE THREAD

**Issue by Codeaddict7423** [mediafront/osmplayer#45]
Hello,
I have just started using the OSM player with the playlist.xml file.  When I attempt to connect to an _.mp4 file in my local directory, the player does not show the movie file.  Only when I point the  <location> </location>to an internet address do the movie files load and play.  When I try to point the location to something like  <location>\Reserve_Videos\_.mp4</location>, the player does not seem to find the file.

ANY HELP would be greatly appreciated. 
Thank you in advance for your time.

**Comment by travist** [comment]
This player is not a local media player... it is meant to only play resources on the web and I cannot guarantee that it would work well locally.
