### ISSUE TITLE
Control Bar fails on second playing of a Youtube Video

### ISSUE THREAD

**Issue by ghost** [mediafront/osmplayer#48]
Everything works great on the initial playing of a youtube video, pausing, playing, scrubbing, all fine.

On the second playing, the control bar becomes un-responsive.  You can replay the video by clicking the play button in the center of the video but not by the controller bar.  After clcking the play button in the middle of the video display, the video will play, but the timeline is not updated nor is the time display.

I see the same behavior in my stand-alone install of the player and on the mediafront demo
http://mediafront.org/osmplayer/#.UYkZt_GGJTN

I am seeing this on Chrome and Firefox on both Windows and Ubuntu.  Have not tested it on IE.

**Comment by timodwhit** [comment]
+1 I'm seeing the same issue.

**Comment by ethanteague** [comment]
+1 Same problem here.

**Comment by angelrouet** [comment]
+1 Sme problem... please fix it...

**Comment by travist** [comment]
This has been elevated on my priority list so you can expect a fix within the next week.  Thanks.

**Comment by travist** [comment]
It seems it resolved itself.  Probably a bug with the YouTube player on their end that they fixed.

**Comment by angelrouet** [comment]
Thanks, for your reactivity.

**Comment by ghost** [comment]
Hi Travis, 
Thanks for looking at this.  But I am not seeing this resolved.  Even on your site http://mediafront.org/osmplayer/#.UYkZt_GGJTN going to the youtube tab and playing the video to the end then playing it a second time, the entire control bar no longer responds to the video progress, time or play state.
