### ISSUE TITLE
Multiple HTML5 Sources In Playlist

### ISSUE THREAD

**Issue by mverstraete** [mediafront/osmplayer#5]
Please add the ability to specify multiple HTML5 video sources in a playlist.  For example, h.264 and OGG video, so that supported browsers will select which video to play without resorting to flash.

**Comment by travist** [comment]
This will come very soon.  I recognize the importance of this being in place and will try to have it done before 1.0 version.

**Comment by travist** [comment]
This is now fixed.  You can provide an array for the file parameter that provides multiple file types to play and fallback to.  The media player will now chose the best one for the browser.

**Comment by mverstraete** [comment]
I'm having a hard time getting this to work in an XML playlist.  What would the syntax be?  Does it still go in the "location" tag?
