### ISSUE TITLE
Problem with full screen in Google Chrome

### ISSUE THREAD

**Issue by mahzian** [mediafront/osmplayer#57]
Hello, first of all thanks for this player it is excellent! I am having an issue with the full screen function in Google Chrome, where it tries to make the video full screen (you see it for a split second but then goes back to the normal player). It works fine in IE, Firefox and Safari.

Is this a known issue or have I implemented it incorrectly?

Here is my video page:

https://www.rrmeo.com/misc_files/acrrm/acrrm_video/musculo/video.html

Any help would be much appreciated.

**Comment by travist** [comment]
Yeah, I am definitely getting that as well.  This used to work, so I am curious if it was broken with a later release of chrome or OSX.  I will definitely take a look at this since it is pretty bad.

**Comment by travist** [comment]
This should now be fixed with the latest version.
