### ISSUE TITLE
OSMPlayer event ended or onComplete??

### ISSUE THREAD

**Issue by svnlabs** [mediafront/osmplayer#63]
Hello,

I need to detect video finish event in OSMPlayer ... 
I have onComplete() method in javascript ... but I am not sure how you use in this below code ...

<script type="text/javascript">
  $(function() {
    $("video").osmplayer({
      width: '100%',
      height: '600px'
    });
  });
</script>

<video src="http://progressive.totaleclips.com.edgesuite.net/105/e105598_257.mp4" poster="http://www.movieposter.com/posters/archive/main/143/MPW-71686"></video>

Thanks

**Comment by svnlabs** [comment]
Oh... code was missed in last thread ...

$(function() {
    $("video").osmplayer({
      width: '100%',
      height: '600px'
    });
  });

Thx

**Comment by travist** [comment]
You can simply trigger like this.

```
$(function() {
  minplayer.get('media', function(media) {
    media.bind('ended', function() {
      console.log('The media is done!');
    });
  });
});
```
