### ISSUE TITLE
Parse Error in PHP4 and PHP5

### ISSUE THREAD

**Issue by mike760534211** [mediafront/osmplayer#7]
Open Standard Media (OSM) Player v.97 & 0.98
Parse error: syntax error, unexpected T_STRING, expecting T_OLD_FUNCTION or T_FUNCTION or T_VAR or '}' in /****_**/__/_*******/htdocs/player/OSMPlayer.php on line 45.

**Comment by travist** [comment]
Should be fixed with version 1.0-rc1
