### ISSUE TITLE
Template does not load using PHP library.

### ISSUE THREAD

**Issue by mverstraete** [mediafront/osmplayer#8]
When using the PHP library to load the player, the template does not seem to load at all.  CSS files are not generated either.  Tested using the sample index.html and index.php included with the download in 1.0-beta2.  This worked in the 2010-12-31 commit (95a2ec3).  It stopped working in the 2011-01-08 commit (57d6342).

**Comment by travist** [comment]
This is not fixed with the version 1.0-rc1 release.
